### PR TITLE
Reset ball speed & point ball towards enemy on score

### PR DESCRIPTION
**Pull request by quantumpotato**
Preventing breakout style score loop behind the paddle.

pongo

Note: the ball can move too fast for the paddle to catch. You may have to calculate the ball's X & Y vector to do this:

```
if (ball is one or greater vector step away from the paddle it's heading towards) {
     move ball its full vector this step
} else {
    #the ball is moving at say, v[:x] = -10 but ball.x = 2.
    #calculate percentage of total vector distance away the ball is from its target paddle
    #move ball by that amount, allowing for paddle collision
    #otherwise the ball would move -10 and go through the paddle
}
```

### CODE REVIEW

**Comment by subdigital** [comment]
I noticed this as well, but didn't have a good fix for it at the moment. This solution is less fun, but avoids the annoying explosion explosion ;)

**Comment by quantumpotato** [comment]
Yeah It is kind of fun rapid scoring like that. Maybe a power up?

Congratulations for shipping your first game!!!

**Comment by subdigital** [comment]
I started to get a lot of ideas for power-ups / curses that make the game more interesting.
- shrunken/larger paddle for 15 seconds
- clouds covering 50% of the middle of the screen
- fake balls of slightly different color
- shoot stun missiles at your opponent that makes them move slower (or stop)

Anyway, some fun ideas, but I want to move onto other games :)

**Comment by quantumpotato** [comment]
Hah, fakes would be hilarious.

Makes sense. Looking forward to playing what you create!

**Pull request merged**
